export const oobStateData = {
  // WARLORD
  warlord: {
    name: '',
    warscroll: '',
    commandTrait: '',
    coreEnhancement: '',
    injury: '',
    renownPoints: 0,
    points: 0,
  },
  // HEROES
  hero1Name: '',
  hero1Warscroll: '',
  hero1CommandTrait: '',
  hero1CoreEnhancement: '',
  hero1Injury: '',
  hero1RenownPoints: 0,
  hero1Points: 0,
  hero2Name: '',
  hero2Warscroll: '',
  hero2CommandTrait: '',
  hero2CoreEnhancement: '',
  hero2Injury: '',
  hero2RenownPoints: 0,
  hero2Points: 0,
  hero3Name: '',
  hero3Warscroll: '',
  hero3CommandTrait: '',
  hero3CoreEnhancement: '',
  hero3Injury: '',
  hero3RenownPoints: 0,
  hero3Points: 0,
  // OTHER UNITS
  unit1Name: '',
  unit1Warscroll: '',
  unit1VeteranAbilities: '',
  unit1Reinforced1: false,
  unit1Reinforced2: false,
  unit1CasualtyScore: 0,
  unit1RenownPoints: 0,
  unit1Points: 0,
  // ORDER OF BATTLE LIMITS
  totalUnits: 6,
  heroes: 3,
  monsters: 1,
  warMachines: 1,
  wizards: 1,
  priests: 1,
  reinforcedUnits: 1,
  allies: 1,
};