export const ptgStateData = {
  playerName: '',
  armyName: '',
  faction: '',
  subfaction: '',
  realmOfOrigin: '',
  startingSize: 'ヴァンガード (600pt)',
  // QUEST LOG
  questLog: {
    current: '',
    reward: '',
    progress: '',
  },
  // GLORY POINTS
  gloryPoints: 0,
  // STRONGHOLD
  stronghold: {
    name: '',
    barracks: 0,
    hasImposing: false,
    hasMighty: false,
  },
  // ARCHIVEMENTS
  archivements: {
    battleFought: 0,
    victoriesWon: 0,
    questsCompleted: 0,
    enemyHeroesSlain: 0,
  },
  // THE VAULT
  theVault: {
    artefact1: '',
    artefact2: '',
    artefact3: '',
    artefact4: '',
    artefact5: '',
    artefact6: '',
    spell1: '',
    spell2: '',
    spell3: '',
    spell4: '',
    spell5: '',
    spell6: '',
    prayer1: '',
    prayer2: '',
    prayer3: '',
    prayer4: '',
    prayer5: '',
    prayer6: '',
    uniqueEnhancement1: '',
    uniqueEnhancement2: '',
    uniqueEnhancement3: '',
    uniqueEnhancement4: '',
    uniqueEnhancement5: '',
    uniqueEnhancement6: '',
    endlessSpell1: '',
    endlessSpell2: '',
    endlessSpell3: '',
    triumph: '',
    battalion1: '',
    battalion2: '',
    battalion3: '',
    battalion4: '',
    battalion5: '',
    battalion6: '',
  },
  territories: {
    stronghold: {
      territory1: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory2: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory3: {
        name: '',
        type: '',
        isUpgraded: false,
      },
    },
    imposing: {
      territory1: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory2: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory3: {
        name: '',
        type: '',
        isUpgraded: false,
      },
    },
    mighty: {
      territory1: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory2: {
        name: '',
        type: '',
        isUpgraded: false,
      },
      territory3: {
        name: '',
        type: '',
        isUpgraded: false,
      },
    },
  },
  // WARLORD
  warlord: {
    name: '',
    warscroll: '',
    commandTrait: '',
    coreEnhancement: '',
    injury: '',
    renownPoints: 0,
    points: 0,
  },
  // HEROES
  heroes: {
    hero1: {
      name: '',
      warscroll: '',
      commandTrait: '',
      coreEnhancement: '',
      injury: '',
      renownPoints: 0,
      points: 0,
    },
    hero2: {
      name: '',
      warscroll: '',
      commandTrait: '',
      coreEnhancement: '',
      injury: '',
      renownPoints: 0,
      points: 0,
    },
    hero3: {
      name: '',
      warscroll: '',
      commandTrait: '',
      coreEnhancement: '',
      injury: '',
      renownPoints: 0,
      points: 0,
    },
  },
  // OTHER UNITS
  otherUnits: {
    unit1: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit2: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit3: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit4: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit5: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit6: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit7: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit8: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit9: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit10: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit11: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
    unit12: {
      name: '',
      warscroll: '',
      veteranAbilities: '',
      reinforced1: false,
      reinforced2: false,
      casualtyScore: 0,
      renownPoints: 0,
      points: 0,
    },
  },
  // ORDER OF BATTLE LIMITS
  orderOfBattleLimits: {
    totalUnits: 6,
    heroes: 3,
    monsters: 1,
    warMachines: 1,
    wizards: 1,
    priests: 1,
    reinforcedUnits: 1,
    allies: 1,
  },
};